### ISSUE TITLE
不错，个人认为该库有以下缺陷

### ISSUE THREAD

**Issue by loper7** [Eclipse-Kio/MentionEditText#1]
1.一次性插入多条逻辑存在问题（这个我自行处理了一下，需要的话我可提供pr）
2.没有数据恢复方法（应用场景:编辑完成之后保存到草稿箱，然后从草稿箱取值恢复编辑）
开源不易，加油~

**Comment by Elip-kio** [comment]
非常感谢，目前@和插入span是分开的，这个地方确实会有些问题，老兄可以提个PR让我参考改进下😼😼

**Comment by Elip-kio** [comment]
另外数据恢复这里是需要自行处理了，后期会再考虑加入存储与恢复

**Comment by loper7** [comment]
项目中遇到一个新需求，借鉴了你的思路自己写了一个耦合本身业务逻辑的组件，后面有空了我可以抽离一下业务逻辑放出来一起学习学习~_~

**Comment by Elip-kio** [comment]
可以的
