### ISSUE TITLE
double method call

### ISSUE THREAD

**Issue by Sperance** [Eclipse-Kio/MentionEditText#2]
![image](https://user-images.githubusercontent.com/43790253/149346034-2e3b4b95-2b9e-4b99-8f58-d90d8974d62f.png)
![image](https://user-images.githubusercontent.com/43790253/149346128-ddb8db79-2fba-41cc-a240-1bb00ef52e7b.png)

**Comment by Elip-kio** [comment]
Thanks for your feed back, Do you mean the callback `onMentionInserted` will be called twice? If so, you can check the following reasons:

* Did you ever called the `automaticallyAppend` function?  This function is used for the cases that not triggered by the users but programmatically, so you don't need to invoke it mannually.
* Did you ever implemented your own `TextWather` that might conflict with this lib.

By the way, the statement `MainActivity.supportFragmentMannger` seems odd, If it is an instance then it's name should not starts with capital letter and should not be stored in other class.
